// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package c37pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C37DataFrame struct {
	StationName          string           `protobuf:"bytes,1,opt,name=stationName,proto3" json:"stationName,omitempty"`
	IdCode               uint32           `protobuf:"varint,2,opt,name=idCode,proto3" json:"idCode,omitempty"`
	NominalFrequency     uint32           `protobuf:"varint,3,opt,name=nominalFrequency,proto3" json:"nominalFrequency,omitempty"`
	PhasorChannels       []*PhasorChannel `protobuf:"bytes,4,rep,name=phasorChannels,proto3" json:"phasorChannels,omitempty"`
	ScalarChannels       []*ScalarChannel `protobuf:"bytes,5,rep,name=scalarChannels,proto3" json:"scalarChannels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *C37DataFrame) Reset()         { *m = C37DataFrame{} }
func (m *C37DataFrame) String() string { return proto.CompactTextString(m) }
func (*C37DataFrame) ProtoMessage()    {}
func (*C37DataFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_cb5b7164a1348a25, []int{0}
}
func (m *C37DataFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C37DataFrame.Unmarshal(m, b)
}
func (m *C37DataFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C37DataFrame.Marshal(b, m, deterministic)
}
func (dst *C37DataFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C37DataFrame.Merge(dst, src)
}
func (m *C37DataFrame) XXX_Size() int {
	return xxx_messageInfo_C37DataFrame.Size(m)
}
func (m *C37DataFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_C37DataFrame.DiscardUnknown(m)
}

var xxx_messageInfo_C37DataFrame proto.InternalMessageInfo

func (m *C37DataFrame) GetStationName() string {
	if m != nil {
		return m.StationName
	}
	return ""
}

func (m *C37DataFrame) GetIdCode() uint32 {
	if m != nil {
		return m.IdCode
	}
	return 0
}

func (m *C37DataFrame) GetNominalFrequency() uint32 {
	if m != nil {
		return m.NominalFrequency
	}
	return 0
}

func (m *C37DataFrame) GetPhasorChannels() []*PhasorChannel {
	if m != nil {
		return m.PhasorChannels
	}
	return nil
}

func (m *C37DataFrame) GetScalarChannels() []*ScalarChannel {
	if m != nil {
		return m.ScalarChannels
	}
	return nil
}

type PhasorChannel struct {
	ChannelName          string    `protobuf:"bytes,1,opt,name=channelName,proto3" json:"channelName,omitempty"`
	Unit                 string    `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Data                 []*Phasor `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PhasorChannel) Reset()         { *m = PhasorChannel{} }
func (m *PhasorChannel) String() string { return proto.CompactTextString(m) }
func (*PhasorChannel) ProtoMessage()    {}
func (*PhasorChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_cb5b7164a1348a25, []int{1}
}
func (m *PhasorChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhasorChannel.Unmarshal(m, b)
}
func (m *PhasorChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhasorChannel.Marshal(b, m, deterministic)
}
func (dst *PhasorChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhasorChannel.Merge(dst, src)
}
func (m *PhasorChannel) XXX_Size() int {
	return xxx_messageInfo_PhasorChannel.Size(m)
}
func (m *PhasorChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_PhasorChannel.DiscardUnknown(m)
}

var xxx_messageInfo_PhasorChannel proto.InternalMessageInfo

func (m *PhasorChannel) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *PhasorChannel) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *PhasorChannel) GetData() []*Phasor {
	if m != nil {
		return m.Data
	}
	return nil
}

type Phasor struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Angle                float64  `protobuf:"fixed64,2,opt,name=angle,proto3" json:"angle,omitempty"`
	Magnitude            float64  `protobuf:"fixed64,3,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Phasor) Reset()         { *m = Phasor{} }
func (m *Phasor) String() string { return proto.CompactTextString(m) }
func (*Phasor) ProtoMessage()    {}
func (*Phasor) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_cb5b7164a1348a25, []int{2}
}
func (m *Phasor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phasor.Unmarshal(m, b)
}
func (m *Phasor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phasor.Marshal(b, m, deterministic)
}
func (dst *Phasor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phasor.Merge(dst, src)
}
func (m *Phasor) XXX_Size() int {
	return xxx_messageInfo_Phasor.Size(m)
}
func (m *Phasor) XXX_DiscardUnknown() {
	xxx_messageInfo_Phasor.DiscardUnknown(m)
}

var xxx_messageInfo_Phasor proto.InternalMessageInfo

func (m *Phasor) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Phasor) GetAngle() float64 {
	if m != nil {
		return m.Angle
	}
	return 0
}

func (m *Phasor) GetMagnitude() float64 {
	if m != nil {
		return m.Magnitude
	}
	return 0
}

type ScalarChannel struct {
	ChannelName          string    `protobuf:"bytes,1,opt,name=channelName,proto3" json:"channelName,omitempty"`
	Unit                 string    `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Data                 []*Scalar `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ScalarChannel) Reset()         { *m = ScalarChannel{} }
func (m *ScalarChannel) String() string { return proto.CompactTextString(m) }
func (*ScalarChannel) ProtoMessage()    {}
func (*ScalarChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_cb5b7164a1348a25, []int{3}
}
func (m *ScalarChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarChannel.Unmarshal(m, b)
}
func (m *ScalarChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarChannel.Marshal(b, m, deterministic)
}
func (dst *ScalarChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarChannel.Merge(dst, src)
}
func (m *ScalarChannel) XXX_Size() int {
	return xxx_messageInfo_ScalarChannel.Size(m)
}
func (m *ScalarChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarChannel.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarChannel proto.InternalMessageInfo

func (m *ScalarChannel) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *ScalarChannel) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *ScalarChannel) GetData() []*Scalar {
	if m != nil {
		return m.Data
	}
	return nil
}

type Scalar struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scalar) Reset()         { *m = Scalar{} }
func (m *Scalar) String() string { return proto.CompactTextString(m) }
func (*Scalar) ProtoMessage()    {}
func (*Scalar) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_cb5b7164a1348a25, []int{4}
}
func (m *Scalar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scalar.Unmarshal(m, b)
}
func (m *Scalar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scalar.Marshal(b, m, deterministic)
}
func (dst *Scalar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scalar.Merge(dst, src)
}
func (m *Scalar) XXX_Size() int {
	return xxx_messageInfo_Scalar.Size(m)
}
func (m *Scalar) XXX_DiscardUnknown() {
	xxx_messageInfo_Scalar.DiscardUnknown(m)
}

var xxx_messageInfo_Scalar proto.InternalMessageInfo

func (m *Scalar) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Scalar) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*C37DataFrame)(nil), "c37pb.C37DataFrame")
	proto.RegisterType((*PhasorChannel)(nil), "c37pb.PhasorChannel")
	proto.RegisterType((*Phasor)(nil), "c37pb.Phasor")
	proto.RegisterType((*ScalarChannel)(nil), "c37pb.ScalarChannel")
	proto.RegisterType((*Scalar)(nil), "c37pb.Scalar")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_cb5b7164a1348a25) }

var fileDescriptor_messages_cb5b7164a1348a25 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xb1, 0x6e, 0x83, 0x30,
	0x10, 0x95, 0x4b, 0x82, 0x94, 0x4b, 0x13, 0x55, 0x56, 0x54, 0x31, 0x74, 0xa0, 0x4c, 0xa8, 0x03,
	0x43, 0x18, 0xb2, 0x74, 0xa3, 0xca, 0x58, 0x45, 0xee, 0x17, 0x5c, 0xc0, 0x02, 0x4b, 0x60, 0x53,
	0x6c, 0x2a, 0xf5, 0xaf, 0xfb, 0x09, 0x15, 0x36, 0x6a, 0x20, 0x55, 0xb7, 0x6e, 0xf7, 0xde, 0xdd,
	0x3d, 0xbf, 0x77, 0x32, 0x6c, 0x1b, 0xae, 0x35, 0x96, 0x5c, 0x27, 0x6d, 0xa7, 0x8c, 0xa2, 0xcb,
	0x3c, 0x3d, 0xb4, 0xe7, 0xe8, 0x8b, 0xc0, 0x6d, 0x96, 0x1e, 0x5e, 0xd0, 0xe0, 0xb1, 0xc3, 0x86,
	0xd3, 0x10, 0xd6, 0xda, 0xa0, 0x11, 0x4a, 0xbe, 0x62, 0xc3, 0x03, 0x12, 0x92, 0x78, 0xc5, 0xa6,
	0x14, 0xbd, 0x07, 0x5f, 0x14, 0x99, 0x2a, 0x78, 0x70, 0x13, 0x92, 0x78, 0xc3, 0x46, 0x44, 0x9f,
	0xe0, 0x4e, 0xaa, 0x46, 0x48, 0xac, 0x8f, 0x1d, 0x7f, 0xef, 0xb9, 0xcc, 0x3f, 0x03, 0xcf, 0x4e,
	0xfc, 0xe2, 0xe9, 0x33, 0x6c, 0xdb, 0x0a, 0xb5, 0xea, 0xb2, 0x0a, 0xa5, 0xe4, 0xb5, 0x0e, 0x16,
	0xa1, 0x17, 0xaf, 0xf7, 0xbb, 0xc4, 0xda, 0x4a, 0x4e, 0xd3, 0x26, 0xbb, 0x9a, 0x1d, 0xb6, 0x75,
	0x8e, 0x35, 0x5e, 0xb6, 0x97, 0xb3, 0xed, 0xb7, 0x69, 0x93, 0x5d, 0xcd, 0x46, 0x15, 0x6c, 0x66,
	0xf2, 0x43, 0xe4, 0xdc, 0x95, 0xd3, 0xc8, 0x13, 0x8a, 0x52, 0x58, 0xf4, 0x52, 0x18, 0x1b, 0x78,
	0xc5, 0x6c, 0x4d, 0x1f, 0x61, 0x51, 0xa0, 0xc1, 0xc0, 0xb3, 0x4f, 0x6f, 0x66, 0xc6, 0x99, 0x6d,
	0x45, 0x27, 0xf0, 0x1d, 0x1e, 0x04, 0x8c, 0x18, 0xb5, 0x3d, 0x66, 0x6b, 0xba, 0x83, 0x25, 0xca,
	0xb2, 0x76, 0x67, 0x24, 0xcc, 0x01, 0xfa, 0x00, 0xab, 0x06, 0x4b, 0x29, 0x4c, 0x5f, 0x70, 0x7b,
	0x3e, 0xc2, 0x2e, 0xc4, 0xe0, 0x7d, 0x16, 0xee, 0x5f, 0xbd, 0x3b, 0xe5, 0xd1, 0xfb, 0x1e, 0x7c,
	0x87, 0xff, 0xf2, 0xfe, 0x81, 0x75, 0xff, 0xe3, 0xdd, 0x82, 0xb3, 0x6f, 0xbf, 0x56, 0xfa, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xaa, 0x6c, 0x59, 0x87, 0x6c, 0x02, 0x00, 0x00,
}
